### ISSUE TITLE
json streamer broken

### ISSUE THREAD

**Issue by rlgomes** [rlgomes/flume#20]
``` bash
> echo "[{}]" | flume "read('stdio', format='json') | write('stdio')"
[{}]



Traceback (most recent call last):
  File "/home/rlgomes/workspace/python/flume/env/bin/flume", line 9, in <module>
    load_entry_point('flume==0.3.2', 'console_scripts', 'flume')()
  File "/home/rlgomes/workspace/python/flume/env/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/rlgomes/workspace/python/flume/env/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/rlgomes/workspace/python/flume/env/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rlgomes/workspace/python/flume/env/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/rlgomes/workspace/python/flume/env/lib/python2.7/site-packages/flume-0.3.2-py2.7.egg/flume/cli.py", line 50, in main
    eval(program, globals(), locals()).execute(loglevel=loglevel)
  File "/home/rlgomes/workspace/python/flume/env/lib/python2.7/site-packages/flume-0.3.2-py2.7.egg/flume/core.py", line 295, in execute
    self.parent.execute(wait=wait, loglevel=loglevel)
  File "/home/rlgomes/workspace/python/flume/env/lib/python2.7/site-packages/flume-0.3.2-py2.7.egg/flume/core.py", line 307, in execute
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/home/rlgomes/workspace/python/flume/env/lib/python2.7/site-packages/flume-0.3.2-py2.7.egg/flume/core.py", line 262, in run
    self.loop()
  File "/home/rlgomes/workspace/python/flume/env/lib/python2.7/site-packages/flume-0.3.2-py2.7.egg/flume/sources/read.py", line 32, in loop
    for points in self.read():
  File "/home/rlgomes/workspace/python/flume/env/lib/python2.7/site-packages/flume-0.3.2-py2.7.egg/flume/adapters/stdio.py", line 79, in read
    strip_ansi=self.strip_ansi)):
  File "/home/rlgomes/workspace/python/flume/env/lib/python2.7/site-packages/flume-0.3.2-py2.7.egg/flume/adapters/streamers/jsoner.py", line 19, in read
    for point in ijson.items(stream, 'item'):
  File "build/bdist.linux-x86_64/egg/ijson/common.py", line 138, in items
  File "build/bdist.linux-x86_64/egg/ijson/common.py", line 65, in parse
  File "build/bdist.linux-x86_64/egg/ijson/backends/python.py", line 185, in basic_parse
  File "build/bdist.linux-x86_64/egg/ijson/backends/python.py", line 129, in parse_value
ijson.common.IncompleteJSONError: Incomplete JSON data
```

**Comment by rlgomes** [comment]
Will fix and write the missing unit tests
